apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-producer
  annotations:
    netscaler.applecloud.io/service.class: netscaler.v2
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: rabbitmq-producer